<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateApplicationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('applications', function (Blueprint $table) {
            $table->bigIncrements('id');

            //application document
            $table->string('document_number')->nullable()->comment = "Will be added if new application";
            $table->string('document_name');
            $table->string('document_revision_number');

            //application details
            $table->integer('document_category')->comment = "1 - PGS, 2 - PQS, 3 - PPS, 4 - WI, 5 - PP, 6 - FMEA, 7 - CP, 8 - IG, 9 - Others";
            $table->integer('document_type')->comment = "1 - New Document, 2 - Revised";
            $table->integer('for_group')->comment = "1 - Operations, 2 - Support Group";
            $table->integer('department')->comment = "from Departments table in RapidX";

            //application pointpersons
            $table->integer('application_originator')->comment = "User from RapidX";
            $table->integer('application_section_head')->comment = "User from Rapidx";
            $table->integer('application_qs_inspector')->comment = "User from RapidX";

            //attached document
            $table->string('aidrc_filename')->comment = "Auto-generated by System";
            $table->string('original_filename')->comment = "Original Uploaded Filename";

            //application status
            $table->integer('status')->comment = "1 - Application Filed, 2 - Approved by Section Head, 3 - QS Inspection Filed, 4 - Approved, for Initial DCC, 5 - Minor Revisions, 6 - Major Revisions, 7 - DCC Approved, for Control, 8 - Controlled";

            $table->timestamps();

            $table->integer('logdel')->comment = "0 - Active, 1 - Inactive";
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('applications');
    }
}
