<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateApplicationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('applications', function (Blueprint $table) {
            $table->bigIncrements('id');

            $table->string('aidrc_control_number');
            $table->string('document_number')->nullable();
            $table->string('document_name');
            $table->integer('document_revision_number');
            $table->integer('document_category');
            $table->integer('document_type');
            $table->integer('for_group');
            $table->integer('department');
            $table->integer('application_originator');
            $table->integer('application_section_head')->nullable()->comment = "For SG/PPC - WHS";
            $table->integer('application_prod_head')->nullable()->comment = "For Operations";
            $table->integer('application_qc_head')->nullable()->comment = "For Operations";
            $table->integer('application_eng_head')->nullable()->comment = "For Operations";
            $table->integer('qs_inspector')->nullable()->comment = "For Operations";
            $table->integer('approver_priority')->nullable()->comment = "1 - Production, 2 - QC, 3 - Engineering";

            $table->longText('originator_remarks');

            $table->string('aidrc_filename')->comment = "Auto-generated by the system";
            $table->string('original_filename')->comment = "Original Uploaded Filename";

            $table->string('excel_filename')->comment = "Auto-generated by the system";
            $table->string('aidrc_excel_filename')->comment = "Original Uploaded Filename";

            $table->integer('status')->comment = "1 - Application Filed, 2 - QC Validated OK, 3 - QC Validated NG, 4 - First Approver OK, 5 - First Approver NG, 6 - Secondary Approvers OK, 7 - Secondary Approvers NG, 8 - For DCC Validation, 9 - For Minor Revisions, 10 - For Major Revisions, 11 - For Document Control, 12 - Cancelled";

            $table->timestamps();

            $table->integer('logdel')->comment = "0 - active, 1 - inactive";
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('applications');
    }
}
