<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateExternalApplicationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('external_applications', function (Blueprint $table){
            $table->bigIncrements('id');
            $table->tinyInteger('status')->default(0)->comment ='0 - Pending, 1 - Done';
            $table->unsignedBigInteger('application_id')->comment ='ID from applications(table)';

            $table->string('external_aidrc_filename')->comment = "Auto-generated by the system";
            $table->string('external_original_filename')->comment = "Original Re-Uploaded Filename";

            $table->string('external_excel_filename')->comment = "Auto-generated by the system";
            $table->string('external_aidrc_excel_filename')->comment = "Original Uploaded Filename";

            $table->string('remarks')->nullable();

            $table->unsignedBigInteger('created_by')->nullable();
            $table->unsignedBigInteger('last_updated_by')->nullable();
            $table->softDeletes()->comment ='0-Active, 1-Deleted';
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('external_applications');
    }
}
