<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddColumnToExternalApplicationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('external_applications', function (Blueprint $table) {
            $table->string('orig_aidrc_filename')->after('application_id')->comment('Auto-generated by the system');
            $table->string('orig_original_filename')->nullable()->after('application_id')->comment('Original Uploaded Filename');

            $table->string('orig_excel_filename')->after('application_id')->comment('Auto-generated by the system');
            $table->string('orig_aidrc_excel_filename')->nullable()->after('application_id')->comment('Original Uploaded Filename');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('external_applications', function (Blueprint $table) {
            $table->dropColumn([
            'orig_aidrc_filename',
            'orig_original_filename',
            'orig_excel_filename',
            'orig_aidrc_excel_filename',
        ]);
        });
    }
}
